FROM node:alpine3.16

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /deskshow

# Installing dependencies
COPY ./package*.json /deskshow



RUN npm install --legacy-peer-deps

# Copying all the files in our project
COPY . .

# COPY . /deskshow
EXPOSE 3000
CMD [ "npm","run","dev" ]

