 version: "3" #We specify a version for Compose. Make sure Compose is compatible with Docker
 services:
   client:
     stdin_open: true
     build:
       context: .
       dockerfile: Dockerfile.dev 
     ports:
       - "3000:3000" 
     volumes:
       - "/app/node_modules"
       - "./:/app"
