# Use Node.js as base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to work directory
COPY package.json  .

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the entire app directory to work directory
COPY . .


# Start the development server
CMD ["npm", "run", "dev"]